### ISSUE TITLE
AMTI driver doesn't work with Visual Studio 2017

### ISSUE THREAD

**Issue by claudia-lat** [robotology-playground/forcetorque-yarp-devices#8]
This issue just to keep trace of this behaviour.  @lucaTagliapietra will add more details about it.

**Comment by lucaTagliapietra** [comment]
The issue was basically related to the AMTI Gen 5 ForcePlate SDK.
The SDK is provided pre-build using Visual Studio 2010, while we use to compile everything Visual Studio 2017.
To solve this issue, I installed Visual Studio 2010 Runtime Redistributable (x64) https://www.microsoft.com/it-it/download/details.aspx?id=14632 as suggested by @mbrunettini.

Right now, force platforms up and running on the new Vicon WorkStation.

Closing.
